/* autogenerated by Processing revision 1286 on 2023-05-22 */
import processing.core.*;
import processing.data.*;
import processing.event.*;
import processing.opengl.*;

import java.util.HashMap;
import java.util.ArrayList;
import java.io.File;
import java.io.BufferedReader;
import java.io.PrintWriter;
import java.io.InputStream;
import java.io.OutputStream;
import java.io.IOException;

public class Calculator extends PApplet {

// Ian Turner | Nov 2022 | Calc Project
Button[] numButtons = new Button[10];
Button[] opButtons = new Button[12];
String dVal = "0.0";
boolean left = true;
float l, r, result;
char op = ' ';
int numColor = color(255, 0, 0);
int opC1 = color(0, 255, 0);
int opC2 = color(128, 0, 255);

 public void setup() {
  /* size commented out by preprocessor */;
  opButtons[0] = new Button(500, 400, 200, 200, '=', opC2);
  opButtons[1] = new Button(400, 400, 100, 200, 'C', opC2);
  opButtons[2] = new Button(100, 0, 100, 100, '.', opC2);
  opButtons[3] = new Button(200, 0, 100, 100, '±', opC2);
  opButtons[4] = new Button(200, 100, 100, 100, '+', opC1);
  opButtons[5] = new Button(200, 200, 100, 100, '-', opC1);
  opButtons[6] = new Button(200, 300, 100, 100, '*', opC1);
  opButtons[7] = new Button(200, 400, 100, 100, '÷', opC1);
  opButtons[9] = new Button(200, 500, 100, 100, '√', opC2);
  opButtons[8] = new Button(0, 0, 100, 100, 'S', opC2);
  opButtons[10] = new Button(300, 500, 100, 100, 'π', opC2);
  opButtons[11] = new Button(300, 400, 100, 100, 'e', opC2);
  numButtons[0] = new Button(0, 500, 100, 100, '0', numColor);
  numButtons[1] = new Button(0, 400, 100, 100, '1', numColor);
  numButtons[2] = new Button(0, 300, 100, 100, '2', numColor);
  numButtons[3] = new Button(0, 200, 100, 100, '3', numColor);
  numButtons[4] = new Button(0, 100, 100, 100, '4', numColor);
  numButtons[5] = new Button(100, 500, 100, 100, '5', numColor);
  numButtons[6] = new Button(100, 400, 100, 100, '6', numColor);
  numButtons[7] = new Button(100, 300, 100, 100, '7', numColor);
  numButtons[8] = new Button(100, 200, 100, 100, '8', numColor);
  numButtons[9] = new Button(100, 100, 100, 100, '9', numColor);
}

 public void draw() {
  background(0);
  for (int i = 0; i < numButtons.length; i++) {
    numButtons[i].display();
    numButtons[i].hover(mouseX, mouseY);
    numButtons[i].c2 += 0.1f;
  }
  for (int i = 0; i < opButtons.length; i++) {
    opButtons[i].display();
    opButtons[i].hover(mouseX, mouseY);
    opButtons[i].c2 -= 1;
  }
  updateDisplay();
  fill(0);
  stroke(opButtons[10].c2);
  rect(300, 0, 400, 100);
  fill(255);
  textAlign(CENTER);
  textSize(50);
  text("Calculator", 500, 50);
  textSize(25);
  text("Ian Turner", 500, 85);
}

 public void keyPressed() {
  if (keyCode == 49 || keyCode == 97) {
    handleEvent("1", true);
  } else if (keyCode == 50 || keyCode == 98) {
    handleEvent("2", true);
  } else if (keyCode == 99 || keyCode == 51) {
    handleEvent("3", true);
  } else if (keyCode == 100 || keyCode == 52) {
    handleEvent("4", true);
  } else if (keyCode == 101 || keyCode == 53) {
    handleEvent("5", true);
  } else if (keyCode == 102 || keyCode == 54) {
    handleEvent("6", true);
  } else if (keyCode == 103 || keyCode == 55) {
    handleEvent("7", true);
  } else if (keyCode == 104 || keyCode == 56) {
    handleEvent("8", true);
  } else if (keyCode == 105 || keyCode == 57) {
    handleEvent("9", true);
  } else if (keyCode == 96 || keyCode == 48) {
    handleEvent("0", true);
  } else if (keyCode == 8 || keyCode == 12) {
    handleEvent("C", false);
  } else if (keyCode == 46 || keyCode == 110) {
    handleEvent(".", false);
  } else if (keyCode == 107 || keyCode == 61) {
    handleEvent("+", false);
  } else if (keyCode == 45 || keyCode == 109) {
    handleEvent("-", false);
  } else if (keyCode == 56 || keyCode == 106) {
    handleEvent("*", false);
  } else if (keyCode == 47 || keyCode == 111) {
    handleEvent("/", false);
  } else if (keyCode == 10) {
    handleEvent("=", false);
  }
}

 public void handleEvent(String val, boolean num) {
  if (num && dVal.length() < 20) {
    if (dVal.equals("0.0")) {
      dVal = val;
    } else {
      dVal += val;
    }
    if (left) {
      l = PApplet.parseFloat(dVal);
    } else {
      r = PApplet.parseFloat(dVal);
    }
  } else if (val.equals("C")) {
    dVal = "0.0";
    left = true;
    op = ' ';
    l = 0.0f;
    r = 0.0f;
    result = 0.0f;
  } else if (val.equals(".")) {
    if (!dVal .contains(".")) {
      dVal += ".";
    }
  } else if (val.equals("+")) {
    op = '+';
    dVal = "0.0";
    left = false;
  } else if (val.equals("-")) {
    op = '-';
    dVal = "0.0";
    left = false;
  } else if (val.equals("*")) {
    op = '*';
    dVal = "0.0";
    left = false;
  } else if (val.equals("/")) {
    op = '÷';
    dVal = "0.0";
    left = false;
  } else if (val.equals("=")) {
    performCalculation();
  } else if (val.equals("π")) {
    performCalculation();
  }
}

 public void mouseReleased() {
  for (int i = 0; i < numButtons.length; i++) {
    if (numButtons[i].on) {
      handleEvent(str(numButtons[i].val), true);
    }
  }

  for (int i = 0; i < opButtons.length; i++) {
    if (opButtons[i].on && opButtons[i].val == 'C') {
      handleEvent(str(opButtons[i].val), false);
    } else if (opButtons[i].on && opButtons[i].val == '+') {
      handleEvent("+", false);
    } else if (opButtons[i].on && opButtons[i].val == '-') {
      handleEvent("-", false);
    } else if (opButtons[i].on && opButtons[i].val == '*') {
      handleEvent("*", false);
    } else if (opButtons[i].on && opButtons[i].val == '÷') {
      handleEvent("/", false);
    } else if (opButtons[i].on && opButtons[i].val == '.') {
      handleEvent(".", false);
    } else if (opButtons[i].on && opButtons[i].val == 'S') {
      if (left) {
        l = sq(l);
        dVal = str(l);
      } else {
        r = sq(r);
        dVal = str(r);
      }
    } else if (opButtons[i].on && opButtons[i].val == '±') {
      if (left) {
        l *= -1;
        dVal = str(l);
      } else {
        r *= -1;
        dVal = str(r);
      }
    } else if (opButtons[i].on && opButtons[i].val == '√') {
      if (left) {
        l = sqrt(l);
        dVal = str(l);
      } else {
        r = sqrt(r);
        dVal = str(r);
      }
    } else if (opButtons[i].on && opButtons[i].val == 'π') {
      if (left) {
        if (l == 0.0f) {
          l = PI;
        } else {
          l *= PI;
        }
        dVal = str(l);
      } else {
        if (r == 0.0f) {
          r = PI;
        } else {
          r *= PI;
        }
        dVal = str(r);
      }
    } else if (opButtons[i].on && opButtons[i].val == 'e') {
      if (left) {
        if (l == 0.0f) {
          l = 2.7182818f;
        } else {
          l *= 2.7182818f;
        }
        dVal = str(l);
      } else {
        if (r == 0.0f) {
          r = 2.7182818f;
        } else {
          r *= 2.7182818f;
        }
        dVal = str(r);
      }
    } else if (opButtons[i].on && opButtons[i].val == '=') {
      handleEvent("=", false);
    }
  }
}

 public void updateDisplay() {
  fill(0);
  stroke(opButtons[10].c2);
  rect(300, 100, 400, 300);
  fill(255);
  textAlign(RIGHT);
  if (dVal.length() < 14) {
    textSize(50);
  } else if (dVal.length() < 15) {
    textSize(48);
  } else if (dVal.length() < 16) {
    textSize(46);
  } else if (dVal.length() < 17) {
    textSize(44);
  } else if (dVal.length() < 18) {
    textSize(42);
  } else if (dVal.length() < 19) {
    textSize(40);
  } else if (dVal.length() < 20) {
    textSize(38);
  } else {
    textSize(36);
  }
  text(dVal, width-25, 375);
}

 public void performCalculation() {
  if (op == '+') {
    result = l + r;
  } else if (op == '-') {
    result = l - r;
  } else if (op == '*') {
    result = l * r;
  } else if (op == '÷') {
    result = l /(r);
  } else {
    result = l;
  }
  dVal = str(result);
  l = result;
  left = true;
}
class Button {
  //Member Variables
  int x, y, w, h;
  char val;
  int c1, c2;
  boolean on;

  // Constructor
  Button(int x, int y, int w, int h, char val, int col) {
    this.x = x;
    this.y = y;
    this.w = w;
    this.h = h;
    this.c2 = col;
    this.val = val;
    c1 = color(0);
    on = false;
  }

   public void display() {
    if (on) {
      fill(c2);
    } else {
      fill(c1);
    }
    stroke(c2);
    rect(x, y, w, h);
    fill(255);
    textAlign(CENTER);
    textSize(50);
    if (val == 'S') {
      text("x²", x + w/2, y + (h/2) + 16.6666666667f);
    } else {
      text(val, x + w/2, y + (h/2) + 16.6666666667f);
    }
  }

   public void hover(int mx, int my) {
    on = (mx > x && mx < x+w && my > y && my < y+h);
  }
}


  public void settings() { size(700, 600); }

  static public void main(String[] passedArgs) {
    String[] appletArgs = new String[] { "--full-screen", "--bgcolor=#666666", "--stop-color=#cccccc", "Calculator" };
    if (passedArgs != null) {
      PApplet.main(concat(appletArgs, passedArgs));
    } else {
      PApplet.main(appletArgs);
    }
  }
}
